name: Send Hekmat

on:
  schedule:
    - cron: '30 3 * * *'
    - cron: '30 9 * * *'
    - cron: '30 13 * * *'
    - cron: '30 17 * * *'
  workflow_dispatch:

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Nasta'liq Font
        run: |
          sudo apt-get install -y fonts-hosny-amiri
          fc-cache -f -q
      - run: pip install requests Pillow arabic-reshaper python-bidi
      - run: python bot.py
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
